cmake_minimum_required(VERSION 3.10.0)
project(main VERSION 0.1.0 LANGUAGES C CXX)

add_executable(main main.cpp)

include(CTest)
enable_testing()
include_directories(${CMAKE_SOURCE_DIR}/include)
file(GLOB_RECURSE SGL_SOURCES "${CMAKE_SOURCE_DIR}/src/sgl/*.cpp")
add_library(sgl STATIC ${SGL_SOURCES})
target_include_directories(sgl PUBLIC ${CMAKE_SOURCE_DIR}/include)
target_link_libraries(main PRIVATE sgl)
set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
include(CPack)
