name: C/C++ CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update >> /dev/null
        sudo apt-get install -y zip g++ cmake curl git libglfw3 libglfw3-dev >> /dev/null
    - name : Download and install precompiled physx binaries
      run: |
        wget https://ghillie575.github.io/phys.zip -O phys.zip
        unzip -o phys.zip
        sudo cp -r phys/include/* /usr/local/include/
        sudo cp -r phys/lib/* /usr/local/lib/
    - name : Install FreeType
      run: |
        git clone https://gitlab.freedesktop.org/freetype/freetype.git
        cd freetype
        mkdir build
        cd build
        cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local
        make -j$(nproc)
        sudo make install
    - name: Configure Project
      run: cmake -S . -B build -DCMAKE_INSTALL_RPATH="\$ORIGIN"

    - name: Build Project
      run: |
        cd build
        cmake --build .

    - name: Package
      run: |
        cd build

        mkdir -p ../out
        mkdir -p ../out/include/SGL
        mkdir -p ../out/lib
        mkdir -p ../out/engine
        mkdir -p ../out/scenes
        mkdir -p ../out/lib
        cmake --install . --prefix ../out
        cp -r ./engine ../out/engine
        cp -r ./scenes ../out/scenes

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-sgl
        path: out
