name: C/C++ CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update >> /dev/null
        sudo apt-get install -y zip g++ cmake curl git libglfw3 libglfw3-dev >> /dev/null

    - name: Configure Project
      run: |
        cmake .

    - name: Build Project
      run: |
        cmake --build . --config Release

    - name: Package
      run: |
        mkdir -p out
        mkdir -p out/include
        cp ./XandO ./out/XandO
        cp -r ./include ./out/SGL/include
        cp ./*.so ./out/
        cp -r ./engine ./out/engine
        cp -r ./scenes ./out/scenes

        timestamp=$(date +"%Y%m%d-%H%M")
        ZIP_FILE_NAME="build-sgl-${timestamp}.zip"
        cd out
        zip -r "${ZIP_FILE_NAME}" *
        mv "${ZIP_FILE_NAME}" ../
        cd ..
    - name: Cleanup
      run: |
        echo 'Cleaning up...'
        rm -rf build
        rm -rf out
        rm -f "${ZIP_FILE_NAME}"
    - name : Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-sgl
        path: build-sgl-*.zip
