name: C/C++ CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update >> /dev/null
        sudo apt-get install -y zip g++ cmake curl git libglfw3 libglfw3-dev >> /dev/null

    - name: Configure Project
      run: cmake -S . -B build -DCMAKE_INSTALL_RPATH="\$ORIGIN"

    - name: Build Project
      run: |
        cd build
        cmake --build .