name: C/C++ CI

on:
  push:
    tags: ["*"]
    branches: ["main"]

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_TYPE: Release
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update >> /dev/null
        sudo apt-get install -y zip g++ cmake curl git libglfw3 libglfw3-dev >> /dev/null

    - name: Configure Project
      run: cmake -S . -B build -DCMAKE_INSTALL_RPATH="\$ORIGIN"

    - name: Build Project
      run: |
        cd build
        cmake --build .

    - name: Package
      run: |
        cd build
        mkdir -p ../out
        mkdir -p ../out/include/SGL
        cp ./XandO ../out/XandO
        cp -r ../include/SGL/* ../out/include/SGL/
        cp ./*.so ../out/
        cp -r ./engine ../out/engine
        cp -r ./scenes ../out/scenes
        cd ../out
        zip -r build-sgl.zip ./*

    - name: Upload Release Asset
      uses: actions/upload-artifact@v4
      with:
        name: build-sgl
        path: out/build-sgl.zip

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use your PAT here
      with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release for tag ${{ github.ref_name }}"
          draft: false
          prerelease: false

    - name: Upload Release Asset to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/build-sgl.zip
        asset_name: build-sgl.zip
        asset_content_type: application/zip
